In [2]:
import pandas as pd
import numpy as np
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer

In [3]:
df = pd.read_table("./SmsCollection.csv" )
df.head(3)

label;text
0  ham;Go until jurong point, crazy.. Available o...
1                  ham;Ok lar... Joking wif u oni...
2  spam;Free entry in 2 a wkly comp to win FA Cup...

In [4]:
df=df.rename(columns={"label;text": "label", "None": "text"})

df[['label','text']]=df['label'].str.split("m;", expand=True)


In [5]:
df.head(3)

label                                               text
0    ha  Go until jurong point, crazy.. Available only ...
1    ha                      Ok lar... Joking wif u oni...
2   spa  Free entry in 2 a wkly comp to win FA Cup fina...

In [6]:
df["label"].replace({"ha": 0, "spa": 1}, inplace=True)
df.head(3)
print(type(df['label']))

<class 'pandas.core.series.Series'>


In [7]:
from sklearn.feature_extraction.text import CountVectorizer

# Instantiate the CountVectorizer method
count_vector = CountVectorizer(ngram_range=(1, 1), lowercase = True , stop_words =  'english')





# Fit the training data and then return the matrix
X = count_vector.fit_transform(df['text']).toarray()

print(X)

y = df['label'].values

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [8]:
from sklearn.model_selection import train_test_split


x_train_spam, x_test_spam, y_train_spam, y_test_spam = train_test_split(X, y, test_size=0.25)

In [9]:

print(x_train_spam)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [ ]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score, confusion_matrix,precision_score
naive_bayes = MultinomialNB()
naive_bayes.fit(x_train_spam , y_train_spam)
predictions = naive_bayes.predict(x_test_spam)


In [ ]:
print(accuracy_score(y_test_spam,predictions))

In [ ]:
print(precision_score(y_test_spam,predictions))